# docker-compose up --build --force-recreate
version: '3.5'
services:
  # http://localhost:15672/#/
  rabbit-mq:
    image: "heidiks/rabbitmq-delayed-message-exchange"
    hostname: "rabbitmq"
    ports:
      - 15672:15672
      - 5672:5672

  # http://localhost:8000/swagger/index.html
  supplier:
    build: RabbitMq.Tutorial.Supplier/
    hostname: "supplier"
    environment:
      - RABBITMQOPTIONS__HOSTNAME=rabbitmq
      - RABBITMQOPTIONS__PORT=5672
    ports:
      - "8000:80"

  # http://localhost:8001
  store-hrusha:
    build: RabbitMq.Tutorial.Store/
    hostname: "store-hrusha"
    environment:
      - RABBITMQOPTIONS__HOSTNAME=rabbitmq
      - RABBITMQOPTIONS__PORT=5672
      - STOREOPTIONS__ID=82B06D3E-90FC-4409-820B-B5383B5173E4
      - STOREOPTIONS__NAME='Hrusha's Goods'
      - STOREOPTIONS__MARKUP=1.2
      - SUPPLIEROPTIONS__HOSTNAME=http://supplier
      - SUPPLIEROPTIONS__PORT=80
    ports:
      - "8001:80"
    external_links:
      - supplier:supplier

  # http://localhost:8002
  store-stepasha:
    build: RabbitMq.Tutorial.Store/
    hostname: "store-stepasha"
    environment:
      - RABBITMQOPTIONS__HOSTNAME=rabbitmq
      - RABBITMQOPTIONS__PORT=5672
      - STOREOPTIONS__ID=531317C9-5457-40C5-8EF3-6358A38587DF
      - STOREOPTIONS__NAME='Stepasha's Store'
      - STOREOPTIONS__MARKUP=1.2
      - SUPPLIEROPTIONS__HOSTNAME=http://supplier
      - SUPPLIEROPTIONS__PORT=80   
    ports:
      - "8002:80"

  # http://localhost:8003
  store-karkusha:
    build: RabbitMq.Tutorial.Store/
    hostname: "store-karkusha"
    environment:
      - RABBITMQOPTIONS__HOSTNAME=rabbitmq
      - RABBITMQOPTIONS__PORT=5672
      - STOREOPTIONS__ID=321B19B5-BB14-419D-B429-DB8EA0C4CD50
      - STOREOPTIONS__NAME='Karkushas's Marketplace'
      - STOREOPTIONS__MARKUP=1.2
      - SUPPLIEROPTIONS__HOSTNAME=http://supplier
      - SUPPLIEROPTIONS__PORT=80
    ports:
      - "8003:80"
